### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by thibaultlavoisey** [macbid/website#15]

**Comment by thibaultlavoisey** [comment]
@ericvence Une idée du contenu de cette page ?

**Comment by ericvence** [comment]
option 1 : un formulaire simple avec nom / email / text area / captcha. Le formulaire envoie à contact@macbidouille.com

option 2 : mailto, mais que l'adresse email soit masquée dans le code pour pas se faire spammer

**Comment by thibaultlavoisey** [comment]
Option 1 ! Une idée du titre, texte de la page ?

**Comment by ericvence** [comment]
#Contactez-nous#

Nous vous invitons à nous contacter pour : 
* partager des actualités
* soumettre un article ou une idée d'article
* une question liée au petites annonces
* nous informer de bugs sur le site ou les forums
* afficher des bandeaux publicitaires si vous êtes annonceur ou régie

Pour obtenir de l'aide concernant l'utilisation de votre Mac, veuillez consulter notre `<a href="https://forum.macbidouille.com" target="_blank">forum</a>`.

**Comment by thibaultlavoisey** [comment]
@ericvence 

Quels champs sont requis ?
Quelle est l'adresse de destination ?
Peux tu me generer un reCAPTCHA ? Pour les domaines suivants : macbidouille.com, macbidouille.dev, macbidouille.local, macbid.com, macbid.dev, macbid.local, dimcab.com, dimcab.dev, dimcab.local, localhost

**Comment by ericvence** [comment]
#### Champs obligatoires
* Message : [text area]
* Captcha

#### Adresse destinataire
* webmaster@macbidouille.com
(qui pointera vers lionel, schlum - un mec des forums, toi et moi)

#### reCaptcha
Cf. mail
