### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by thibaultlavoisey** [macbid/website#16]

**Comment by thibaultlavoisey** [comment]
@ericvence Une idée du contenu de cette page ?

**Comment by ericvence** [comment]
photo/avatar + pseudo + fonction au sein de macbid + liens web optionnels

![team](https://cloud.githubusercontent.com/assets/8094701/7403571/2fc32afe-eed7-11e4-9f39-17f94d7174f4.png)

**Comment by thibaultlavoisey** [comment]
Une idée du titre, texte de la page ?

**Comment by ericvence** [comment]
h1 MacBid

Une équipe de bidouilleurs sympatiques et dédiés qui font vivre ce site et son `<a href="" target="_blank">forum</a>`. Nous suivons une ligne de conduite : partager ce qui nous intéresse et fédérer une communauté de passionnés qui n'ont pas peur d'ouvrir leurs machines.

... puis le tableau ...

**Comment by thibaultlavoisey** [comment]
@ericvence As tu les données concernant la team ou pas encore/pas version définitive ?

**Comment by ericvence** [comment]
Mets ta trogne et pour le reste je gérerai marché que je n'ai pas reçu bcp d'info :/
