### ISSUE TITLE
Edit date rendering?

### ISSUE THREAD

**Issue by thibaultlavoisey** [macbid/website#44]

**Comment by ericvence** [comment]
Tu parles du picker ?

**Comment by thibaultlavoisey** [comment]
Nop, la date de publication des news.

**Comment by ericvence** [comment]
perso ca me va comme ça, mais si t'as envi de faire mieux feel free :)

**Comment by thibaultlavoisey** [comment]
C'est un peu old school, non ?
Je verrais bien quelque chose comme "il y a une heure", "hier", "il y a 2 jours"... Tu en penses quoi ?
J'ai d'autres idées pour améliorer le l'UX, on en parle à mon retour :)

**Comment by ericvence** [comment]
Ah ! j’avais pas compris que tu parlais de ça !
Je suis d’acc, c’est plus sympa “il y a une heure…”

**Comment by thibaultlavoisey** [comment]
Va pour ça :)

**Comment by ericvence** [comment]
Mais qu’au bout d’un certain temps on voit la date, c’est a dire que ce n’est pas interessant de voir : “Il y a 15 jours” -> dans ce cas il vaut mieux la date

**Comment by thibaultlavoisey** [comment]
Dans ce cas comment tu vois ça ?

**Comment by ericvence** [comment]
L'idée est que si c'est le jour même ca dit : 
- a l'instant
- il y a XX minutes
- il y a Y heures et XX minutes

Et que quand ca dépasse un jour ça passe en date :
Lundi 23 Juin 2015, 6h56

(En option : ca affiche l'année que si ce n'est pas l'année en cours :) )
