### ISSUE TITLE
Reduce title size?

### ISSUE THREAD

**Issue by thibaultlavoisey** [macbid/website#47]

**Comment by ericvence** [comment]
Oui mais faut que l’on juge bien
je simule tout ca demain et je te dis

**Comment by thibaultlavoisey** [comment]
Je pense que j'ai une idée.

Par défaut inuitcss est configuré avec des tailles qui vont bien : 16px/24px pour le texte et les titres. J'ai modifié la taille du texte à 14px/21px, mais j'ai pas répercuté ce ratio de modification au taille des titres. Je pense que les titres vont bien avec du texte à 16px. Je vais te donner la taille des titres et on jugera, ça te va ?

**Comment by thibaultlavoisey** [comment]
Car le framework est très bien travaillé pour la typo.

**Comment by thibaultlavoisey** [comment]
Configuration par defaut de inuitcss :

``` css
$inuit-base-font-size:           16px !default;
$inuit-base-line-height:        24px !default;

$inuit-heading-size-1:  36px !default;
$inuit-heading-size-2:  30px !default;
$inuit-heading-size-3:  24px !default;
$inuit-heading-size-4:  20px !default;
$inuit-heading-size-5:  16px !default;
$inuit-heading-size-6:  14px !default;
```

Configuration actuelle : 

``` css
$inuit-base-font-size:           14px !default;
$inuit-base-line-height:        21px !default;

$inuit-heading-size-1:  36px !default;
$inuit-heading-size-2:  30px !default;
$inuit-heading-size-3:  24px !default;
$inuit-heading-size-4:  20px !default;
$inuit-heading-size-5:  16px !default;
$inuit-heading-size-6:  14px !default;
```

Du coup en respectant l'aspect ratio ça devrait plutôt donner ça :

``` css
$inuit-base-font-size:           14px !default;
$inuit-base-line-height:        21px !default;

$inuit-heading-size-1:  32px !default;
$inuit-heading-size-2:  26px !default;
$inuit-heading-size-3:  21px !default;
$inuit-heading-size-4:  18px !default;
$inuit-heading-size-5:  14px !default;
$inuit-heading-size-6:  12px !default;
```

J'ai testé et ça le fait. Les meta des news en 12, comme la toolbar et le footer. C'est un peu mieux.

**Comment by ericvence** [comment]
OK c’est une bonne option

**Comment by thibaultlavoisey** [comment]
J'attrape ça demain. J'en profiterais pour mettre le lien de l'auteur et celui de la source en bleu. Si tu veux que j'attrape le rendu de la date réponds moi dans l'issue appropriée :)
