### ISSUE TITLE
Ajout vidéo dans redactor

### ISSUE THREAD

**Issue by ericvence** [macbid/website#63]
Ca serait cool que redactor ajoute tout seul
```
<p style="text-align: center;" class="flex-video">
	<iframe src="
```
[lien video rentré dans redactor]
```
" frameborder="0" allowfullscreen="">
	</iframe>
</p>
```
quand on ajoute une vidéo

exemple :
```
<p style="text-align: center;" class="flex-video">
	<iframe src="https://www.youtube.com/embed/p_Z_d7AU2u8" frameborder="0" allowfullscreen="">
	</iframe>
</p>
```

**Comment by thibaultlavoisey** [comment]
Je viens d'essayer, ça ajoute déjà la classe flex-video. Il faut utiliser le bouton 'Insérer une vidéo...' et copier l'URL de la vidéo. Quid ?

**Comment by ericvence** [comment]
my bad
